# Default values for clair.

postgress:
  image: 
  replicaCount: 1

clair:
  image: quay.io/coreos/clair:latest
  replicaCount: 1

  logLevel: info

  resources:
    limits:
      cpu: 2000m
      memory: 2000Mi
    requests:
      cpu: 500m
      memory: 500Mi
