apiVersion: v1
kind: Service
metadata:
  name: clair-clair
spec:
  type: NodePort
  selector:
    app: clair-clair
  ports:
  - name: clair-api
    nodePort: 32159
    port: 6060
    protocol: TCP
    targetPort: 6060
  - name: clair-health
    nodePort: 30273
    port: 6061
    protocol: TCP
    targetPort: 6061